.gitignore, docs/built-on-ipfs-filecoin/about.md, docs/filecoin/about.md, docs/ipfs/about.md, docs/ipld/about.md, docs/libp2p/about.md, docs/pre-requisites/about.md, docs/protocol-labs-toolkits-sdks/about.md
added a /docs directory, and /.gitbook/assets and .gitbook.yml
=> initial version of test repo to add to gitbook

docs/protocol-labs-network/README.md
Closes: https://github.com/protocol/launchpad/pull/42
=> fix: pln summary links now point relative

docs/protocol-labs-network/pl-culture.md
Fix two minor grammatical errors: 
* Space between words
* Ordering of words
=> asynchronouslyworking -> working asynchronously

docs/ipfs/how-ipfs-works.md, docs/ipld/README.md
So, I figured for those of us without a proper CS education, the bits of the CID might not be so... self describing. @rvagg  What do you think about these 'pre-req' concepts added in Readme
=> Added some basic pre-reqs & vocab

docs/filecoin/sealing-proving.md
this is temp - replace with actually uploading video to youtube
=> Add image to fil protocol school for now

docs/protocol-labs-network/pl-culture.md
Fixing Open Source Stewardship link
=> fix: broken link

docs/ipld/README.md
Fixed some minor typos and sentence formations along with few punctuation.
=> fix: Minor typos and sentence corrections

docs/ipld/graphs-merkle-dags.md
Fixed minor spellings and removed a duplicate statement.
@walkerlj0 , Please review and merge.
=> Minor spelilngs fixed.

SUMMARY.md, docs/ipfs/ipfs-api.md
This PR includes a subsection under `IPFS`. The subsection contains:
- An introduction to the IPFS API + Go/JS development ecosystem
- Hands-on exercise using the Go client
Depends on: https://github.com/protocol/launchpad-tutorials/pull/1
=> Subsection: IPFS API

drand.md
Added info to Drand curriculum around the challenges of creating randomness on chain.
=> Added info re: challenges of blockchain randomness

docs/protocol-labs-network/teams-in-pl.md
Please @walkerlj0, verify this is the link we're looking for (the list of companies in the PL Network).
=> Fix PL Network Directory link

docs/ipfs/how-ipfs-works.md, docs/ipfs/ipfs-gateways.md, docs/ipfs/ipfs-public-dht.md, docs/ipld/README.md, docs/protocol-labs-network/pl-culture.md, docs/protocol-labs-network/what-is-pl.md, docs/protocol-labs-network/where-we-headed.md
General grammar, spelling, and url link clean ups
=> General sentencing and url link clean ups

docs/libp2p/README.md
Add [ bracket so "content discovery" appears hyperlinked
=> Fix syntax line 16

docs/ipld/ipld-and-ipfs.md
The latest video is called "[V2_How_IPFS_Deals_with_Files(v2)](https://drive.google.com/drive/folders/1NXXwYLaFWF-QQRzP_HLddho9SR7xDGM-)". It has all the final edits. If there is anything that you see or a suggestion. I can go back and fix them :thumbsup: 
The summary is viewable in the commit
=> V4 ipld and ipfs

docs/ipfs/ipfs-gateways.md, docs/ipld/ipld-and-ipfs.md
Resolves issue #164 
I removed a bunch of URLs that made sense to remove in the pov of a non-technical person to read. Many were unintelligible for even technical residents. Or generally going off on a different tangent
=> IPFS gateway change up

layouts/curriculum/list.html
Added a different book icon to curriculum landing page that is visible in both light and dark modes
=> changes book icon on curric page to be visible in dark mode

content/en/curriculum/ipfs/mutable-content/index.md
Merging content created in Issue #162 & PR #188 to main.
=> Merging ipns content to main

content/en/curriculum/pln/teams-in-pl/index.md
Found a couple of typos while reading through the page :)
=> Fix typos on the teams in PL page

content/en/dev-tools/toolkits/ceramic/index.md, content/en/dev-tools/toolkits/introduction/index.md, content/en/dev-tools/toolkits/pinata/index.md, content/en/dev-tools/toolkits/web3-storage/index.md
Resolves #244 #243 #242 #241 #246 #240 #239
=> fix links & file structure in devtools links

content/en/curriculum/ipld/merkle-dags/index.md
Closes #219. Next steps will be to add the right video and video description. But these are the things it should go through.
=> General video description

content/en/curriculum/libp2p/libp2p-resources.md
Closes #191 
What do you think about this solution?
=> Closes #191

content/en/curriculum/ipfs/objectives/index.md, content/en/curriculum/ipld/objectives/index.md, content/en/curriculum/pln/os-contributing.md, content/en/curriculum/pln/os-stewardship.md
=> Changed weights

content/en/curriculum/ipfs/data-exchange/index.md
- Reworded the sub-goals. I think they reflect better what is meant to be learned in this lesson. 
- Tried to re write the "How Bitswap Works" section so that they make more sense linearly. what do you think?
- sentence fixes, capitalization, etc...
=> Marco's edits to Enols IPFS1.4

assets/js/react/components/PageNavigation.jsx, assets/js/react/services/hooks.js, babel.config.js, config/_default/config.toml, content/en/prerequisites/objectives.md, layouts/curriculum/single.html, layouts/partials/header/header.html, layouts/partials/main/docs-navigation.html, layouts/partials/sidebar/curriculum-menu.html, package-lock.json, package.json
Fixes https://github.com/protocol/launchpad/issues/290 and https://github.com/protocol/launchpad/issues/296
=> Fix page navigation and add React support

content/en/curriculum/ipfs/unixfs/index.md
- Just made some small sentence changes
=> MAR edits to enol's ipfs 1.6

assets/scss/common/_custom.scss
Closes #306 
This PR adds spacing between the bottom of a video and text (`<p>` tags).
=> Added padding to all embeds

content/en/curriculum/libp2p/handlers-tutorial.md
Fixes https://github.com/protocol/launchpad/issues/256
The template and solution is here https://github.com/protocol/launchpad-tutorials/pull/4
=> libp2p handlers tutorial

content/en/curriculum/ipld/content-addressing-cids/index.md
Closes #304. Please view to see guess-timated plan. Should I add anything else to this PR? @Jorropo
Done:
* Added fun example of what emoji multibase is. Copied from https://github.com/ipfs/kubo/blob/master/docs/changelogs/v0.14.md#-emoji-support-in-multibase.
=> Added base256emoji example

content/en/dev-tools/toolkits/template.md
Hello, please add thx
@mrodriguez3313
=> added koii network

content/en/dev-tools/toolkits/template.md
Added markdown headers with a new company to the dev tools section.
@mrodriguez3313 please review!
=> Added Curio to repo

content/en/curriculum/filecoin/how-filecoin-works/index.md
can we also add automated checking to broken links? I think we already have this in the IPFS/Filecoin docs
=> broken link to deals

static/ipfs-404.html
Tested here: https://royal-frog-0132.on.fleek.co/page-does-not-exist
=> Add redirection for not found pages

layouts/shortcodes/aboutpage.html
This PR closes the `li` tag on the about page.
=> Fix html tag on aboutpage

content/en/curriculum/filecoin/introduction/index.md, content/en/curriculum/filecoin/protocol/index.md
Some might find this paper helpful in understanding early on.
=> Adding convenient links incase cadets is curious about the economic 

content/en/curriculum/dev-tools/network-indexer/index.md
Update instructions for the latest version of index-provider. Huge kudos to @GlacierWalrus for helping to debug that issue.
=> Update to the latest version of index-provider

content/en/curriculum/dev-tools/network-indexer/index.md
Changed from "Filecion" --> "Filecoin"
=> Fixed a typo in "Filecoin"

content/en/curriculum/dev-tools/chainsafe/forest.md
Request to include Forest 🌲 - the rust client for the Filecoin network into launchpad curriculum under dev-tools.
=> Include Forest 🌲 into launchpad 

content/en/curriculum/ipfs/mutable-content/index.md
=> fix: typo in PubSub header

content/en/curriculum/dev-tools/network-indexer/index.md
* change namespace filecoin-project to IPNI
* update storetheindex to the latest version
=> Update IPNI tutorial

content/en/curriculum/ipld/ipld-and-ipfs/index.md
I added the video into a place I thought would be a good spot.
=> New IPLD Video

content/en/curriculum/filecoin/how-filecoin-works/index.md
This PR adds a "Getting Started with Filecoin" section to the end of the file. The new section provides an overview of ways for developers to get started learning and building on Filecoin, including:
- Running a local Lotus testnet
- Trying Filecoin examples and tutorials
- Building your own decentralized app
- Participating in the Filecoin community
The Filecoin curriculum needed guidance for developers looking to start interacting with and building on the Filecoin network. The new section gives newcomers a high-level roadmap to begin their Filecoin journey.
A "Getting Started with Filecoin" section was added with details on the steps mentioned above. Minor formatting and link changes were also made to keep the style consistent.
Please review and let me know if any changes are needed to …
=> Add "Getting Started with Filecoin" section 

templates/dev-tool-temp.md
On Friday Feb 10 we will have a meeting about the template for Dev Tools pages & come to a final draft!
=> updating Dev Tools template page

content/en/curriculum/filecoin/past-recorded-sessions.md, content/en/curriculum/ipfs/past-recorded-sessions.md, content/en/curriculum/ipld/past-recorded-sessions.md, content/en/curriculum/libp2p/past-recorded-sessions.md
Beginning to fix links and add other past recordings
=> Adding Past Recorded Sessions to Curriculum
